---
services:
  talosctl:
    image: ghcr.io/siderolabs/talosctl:latest
    container_name: talosctl
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
      - talos:/.talos
      - kube:/.kube
    command: cluster create --wait
  # terminal:
  #   image: terminal
  #   build: .
  #   container_name: terminal
  #   ports:
  #     - "7681:7681"
  #     - "8900-8910:8900-8910"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #     - kube:/root/.kube
  # kubebox:
  #   image: docker.io/astefanutti/kubebox:latest
  #   container_name: kubebox
  #   volumes:
  #     - kube:/home/node/.kube
  cloudcmd:
    image: ghcr.io/prmiguel/kube-cloudcmd:main
    container_name: cloudcmd
    build: .
    ports:
      - "8000:8000"
    volumes:
      - kube:/root/.kube
      - code:/code:ro
  openvscode-server:
    image: ghcr.io/prmiguel/kube-openvscode-server:main
    container_name: openvscode-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - CONNECTION_TOKEN= #optional
      # - CONNECTION_SECRET= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
    volumes:
      - code:/code:rw
      # - /path/to/appdata/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
  lens:
    image: supervisorcom/lens-web
    container_name: lens
    ports:
      - "8080:8080"
    volumes:
      - kube:/root/.kube
  command:
    image: alpine
    container_name: command
    depends_on:
      - talosctl
      - cloudcmd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: /bin/sh -c "sleep 60 && \
      apk add --update docker openrc && \
      rc-update add docker boot && \
      docker network connect talos-default lens && \
      docker network connect talos-default openvscode-server && \
      docker network connect talos-default cloudcmd"
      # docker network connect talos-default terminal && \
    
volumes:
  talos:
  kube:
  code:
