---
services:
  talosctl:
    image: ghcr.io/siderolabs/talosctl:latest
    container_name: talosctl
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
      - talos:/.talos
      - kube:/.kube
    command: cluster create --wait
  terminal:
    image: terminal
    build: .
    container_name: terminal
    ports:
      - "7681:7681"
    volumes:
      - kube:/root/.kube
volumes:
  talos:
  kube:
